apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
  labels:
    app: user-db
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.31.248
    path: /data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pvc
spec:
  selector:
    matchLabels:
      app: user-db
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""