apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  type: ClusterIP
  selector:
    app: user-db
  ports:
    - port: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: mysql:8
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-sec
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: user-db
              mountPath: /var/lib/mysql
      volumes:
        - name: user-db
          persistentVolumeClaim:
            claimName: user-db-pvc
        - name: user-sec
          secret:
            secretName: user-sec