apiVersion: v1
kind: PersistentVolume
metadata:
  name: link-db-pv
  labels:
    app: link-db
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.31.248
    path: /data/link/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: link-db-pvc
spec:
  selector:
    matchLabels:
      app: link-db
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""