apiVersion: v1
kind: Service
metadata:
  name: link-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: link-db
  ports:
    - port: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: link-db
  labels:
    app: link-db
spec:
  serviceName: link-db
  replicas: 1
  selector:
    matchLabels:
      app: link-db
  template:
    metadata:
      labels:
        app: link-db
    spec:
      containers:
        - name: link-db
          image: mysql:8
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: link-sec
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: link-db
              mountPath: /var/lib/mysql
      volumes:
        - name: link-db
          persistentVolumeClaim:
            claimName: link-db-pvc
        - name: link-sec
          secret:
            secretName: link-sec