apiVersion: v1
kind: Service
metadata:
  name: link-sotu-svc
  labels:
    app: link-sotu-svc
spec:
  type: ClusterIP
  selector: 
    app: link-sotu-svc
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-sotu-svc
  labels:
    app: link-sotu-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: link-sotu-svc
  template:
    metadata:
      labels:
        app: link-sotu-svc
    spec:
      containers:
        - name: link-sotu-svc
          image: localhost:5000/k8s-learn-linkmanager-sotu
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: link-sec
                  key: mysql-password
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: link-sotu-volume
              mountPath: /usr/src/app/screenshot
      volumes:
        - name: link-sec
          secret:
            secretName: link-sec
        - name: link-sotu-volume
          persistentVolumeClaim:
            claimName: link-sotu-pvc