apiVersion: v1
kind: Service
metadata:
  name: link-svc
  labels:
    app: link-svc
spec:
  type: ClusterIP
  selector:
    app: link-svc
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-svc
  labels:
    app: link-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: link-svc
  template:
    metadata:
      labels:
        app: link-svc
    spec:
      containers:
        - name: link-svc
          image: localhost:5000/k8s-learn-linkmanager
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8001
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3