apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-learn-usercenter-db
  labels:
    app: usercenter-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usercenter-db
  template:
    metadata:
      labels:
        app: usercenter-db
    spec:
      containers:
        - name: k8s-learn-usercenter-db
          image: mysql:8
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1
              memory: 512Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-learn-usercenter-db
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: usercenter-db